name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --release

      - name: Archive binaries (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: tar czf upchuk-linux.tar.gz -C target/release upchuk

      - name: Archive binaries (macOS)
        if: matrix.platform == 'macos-latest'
        run: tar czf upchuk-macos.tar.gz -C target/release upchuk

      - name: Archive binaries (Windows)
        if: matrix.platform == 'windows-latest'
        run: powershell Compress-Archive -Path target\release\upchuk.exe -DestinationPath upchuk-windows.zip

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            upchuk-linux.tar.gz
            upchuk-macos.tar.gz
            upchuk-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
