name: Build and Release (Linux only)

on:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --release

      - name: Archive binary
        run: tar czf upchuk-linux.tar.gz -C target/release upchuk

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: upchuk-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
